fix: signin and signup fixes. add duplicate record exception
capan/mapptastic-be pull request #9
Opened 2020-11-01 22:01 UTC by capan

2020-11-02 19:32 UTC, zhunor requested changes

2020-11-02 19:32 UTC, zhunor commented on src/services/auth.service.ts
> +  tokens: Record<string, unknown>;
Why we give up on using `Token` interface defined above, i think it is better to have explicit type for this one
https://github.com/capan/mapptastic-be/pull/9/files#diff-40f7172e540c3b96f51825110cded9d3c48f0b5b3726aaa6938b072fcd430225R12

2020-11-02 19:32 UTC, zhunor commented on src/services/auth.service.ts
>          console.error(`Signup err ${err}`);
I don't necessarily think that you wanna `console.error` here as you are already throwing an exception below. I think this is one my temporary additions. You can delete it

2020-11-02 20:28 UTC, capan commented on src/services/auth.service.ts
> +  tokens: Record<string, unknown>;
Token type was mistakenly removed. Now that mistake reverted

2020-11-02 20:28 UTC, capan commented on src/services/auth.service.ts
>          console.error(`Signup err ${err}`);
Express error handler logs the trowed error. `console.error` is surely unnecessary 👍🏼. removed

2020-11-03 08:34 UTC, zhunor requested changes

2020-11-03 08:34 UTC, zhunor commented on src/services/auth.service.ts
> +      // const hashedPassword = await bcrypt.hash(password, saltRound);
We can get rid of this comment, same below

2020-11-03 12:20 UTC, capan commented on src/services/auth.service.ts
> +      // const hashedPassword = await bcrypt.hash(password, saltRound);
done!

2020-11-03 12:24 UTC, capan commented on src/services/auth.service.ts
> +      // const hashedPassword = await bcrypt.hash(password, saltRound);
done

2020-11-03 14:45 UTC, zhunor approved these changes
LGTM ✅

2020-11-03 14:57 UTC, merged